version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - ./env/prod/django.env
      - ./env/prod/postgres.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ['gunicorn', 'config.wsgi']
    stdin_open: true
    tty: true
    networks:
      store_main: {}

  postgres:
    image: postgres:14.0-alpine
    shm_size: '1gb'
    env_file:
      - ./env/local/postgres.env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      store_main: {}

  redis:
    image: redis:6.2.6-alpine
    networks:
      store_main: {}

networks:
  store_main: {}

volumes:
  database: {}
