# Generated by Django 3.2.8 on 2021-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categorytranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslide',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='main.OrderProduct', to='main.Product'),
        ),
        migrations.AlterField(
            model_name='recommendedproductslide',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
