# Generated by Django 3.2.8 on 2021-11-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211010_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
