# Generated by Django 3.2.8 on 2021-11-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_additional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='additionalOptions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='additionalOptionsMeta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='main.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='main.product'),
        ),
    ]
