# Generated by Django 3.2.8 on 2021-11-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_is_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('display', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rates', to='main.currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='main.currency')),
            ],
        ),
    ]
